In [8]:
from aeon.similarity_search._commons import *
from aeon.similarity_search.series_search import *
import numpy as np
from numpy.testing import assert_array_almost_equal

In [2]:
n_samples=2
n_channels=3
query_length=5
X_subs = np.random.rand(n_samples, n_channels, query_length)
q = np.random.rand(n_channels, query_length)

In [3]:
n_columns=5
shift=2
warparound=23

In [4]:
arr=np.random.rand(n_columns)
arr

array([0.09619802, 0.41106643, 0.18914024, 0.63670882, 0.35715271])

In [5]:
res_arr=numba_roll_1D_no_warparound(arr,shift,warparound)
res_arr

array([23.        , 23.        ,  0.09619802,  0.41106643,  0.18914024])

In [48]:
n_rows=2
n_columns=3
shift=2
warparound=14

In [49]:
arr=np.random.rand(n_rows,n_columns)
arr

array([[0.93306621, 0.46541855, 0.80534776],
       [0.86205769, 0.07086389, 0.38304427]])

In [50]:
res_arr=numba_roll_2D_no_warparound(arr,shift,warparound)
res_arr

array([[14.        , 14.        ,  0.93306621],
       [14.        , 14.        ,  0.86205769]])

In [51]:
n_cases=3
n_candidates=4
arr=np.random.rand(n_cases,n_candidates)
arr

array([[0.48656398, 0.42053769, 0.67763485, 0.80750033],
       [0.29294077, 0.85502115, 0.17414422, 0.87988586],
       [0.02714461, 0.57553083, 0.53823929, 0.08922194]])

In [ ]:
res_arr=extract_top_k_and_threshold_from_distance_profiles(arr,k=2)
res_arr

(array([0.02714461, 0.08922194]),
 array([[2, 0],
        [2, 3]]))

In [53]:
p,q=res_arr
p

array([0.02714461, 0.08922194])

In [6]:
n_cases=10
n_candidates=2
arr=np.random.randint(0,10,size=(n_cases,n_candidates))
arr

array([[4, 6],
       [2, 7],
       [3, 6],
       [3, 6],
       [7, 2],
       [3, 0],
       [3, 0],
       [1, 3],
       [7, 0],
       [2, 7]], dtype=int32)

In [7]:
res_arr=extract_top_k_and_threshold_from_distance_profiles_one_series(arr,id_x=2)
res_arr

ValueError: setting an array element with a sequence.

In [49]:
dtype='int64'
X = np.asarray([[[1, 2, 3, 4, 1, 2, 3, 4]]], dtype=dtype)
S = np.asarray([[1, 2, 3]], dtype=dtype)
L = 3

In [50]:
search = SeriesSearch()
search.fit(X)


SeriesSearch()

In [57]:
mp, ip = search.predict(S, L, apply_exclusion_to_result=False)

In [58]:
mp

array([array([0.])], dtype=object)

In [59]:
ip

array([array([[0, 0]])], dtype=object)